CREATE TABLE Questions(id INTEGER PRIMARY KEY AUTOINCREMENT, question_text TEXT, active BIT DEFAULT 1);
CREATE TABLE Choices(qid INTEGER, choice_text TEXT, choice_id INTEGER NOT NULL, FOREIGN KEY(qid) REFERENCES Questions(id) ON DELETE CASCADE);
CREATE TABLE Responses(qid INTEGER, response INTEGER, dt DATETIME, student_id INT, FOREIGN KEY(qid) REFERENCES Questions(id) ON DELETE CASCADE);
