# Generated by Django 3.0.2 on 2020-03-23 20:28

import admin_back.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=20)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_back.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('type', models.IntegerField(choices=[(1, 'RADIO'), (2, 'CHECKBOX')], default=admin_back.models.QuestionTypes['RADIO'])),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_back.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_back.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_back.Survey')),
            ],
        ),
    ]
