# Generated by Django 3.0.2 on 2020-03-31 00:17

import admin_back.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='state',
            field=models.IntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=admin_back.models.QuestionState['ACTIVE']),
        ),
    ]
